from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from typing import Any

from src.application.copilot_context_helpers import dedupe_warnings
from src.models.copilot import (
    CopilotContextBundle,
    CopilotResearchCardRequest,
    CopilotResearchCardResult,
    CopilotSourceRef,
    CopilotToolTrace,
    ResearchCard,
    ResearchClaim,
)
from src.services.copilot_provider import (
    CancelCheck,
    CopilotProvider,
    CopilotRunCancelled,
    RunEventEmitter,
    ToolExecutor,
)


@dataclass
class MockCopilotProvider(CopilotProvider):
    model: str = "gamma-mock-research-card-v1"
    provider_name: str = "mock"

    def stream_research_card(
        self,
        *,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_specs: list[dict[str, object]],
        execute_tool: ToolExecutor,
        emit: RunEventEmitter,
        should_cancel: CancelCheck,
    ) -> CopilotResearchCardResult:
        """Deterministic streaming variant: emits tool and text-delta events
        around the same card the synchronous path produces."""

        def traced_execute(tool_name: str, arguments: dict[str, object], ctx: CopilotContextBundle):
            if should_cancel():
                raise CopilotRunCancelled()
            emit("tool.call", {"tool_name": tool_name, "arguments": arguments})
            execution = execute_tool(tool_name, arguments, ctx)
            emit(
                "tool.result",
                {
                    "tool_name": tool_name,
                    "summary": execution.trace.summary,
                    "source_ids": list(execution.trace.source_ids),
                },
            )
            return execution

        result = self.generate_research_card(
            request=request,
            context=context,
            tool_specs=tool_specs,
            execute_tool=traced_execute,
        )
        text = result.card.hypothesis if result.card is not None else (result.message or "")
        for start in range(0, len(text), 48):
            if should_cancel():
                raise CopilotRunCancelled()
            emit("text.delta", {"delta": text[start : start + 48]})
        return result

    def generate_research_card(
        self,
        *,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_specs: list[dict[str, object]],
        execute_tool: ToolExecutor,
    ) -> CopilotResearchCardResult:
        allowed_tool_names = {
            str(spec.get("name") or "").strip()
            for spec in tool_specs
            if isinstance(spec, dict)
        }
        tool_outputs: dict[str, Any] = {}
        tool_traces: list[CopilotToolTrace] = []
        sources: dict[str, CopilotSourceRef] = {source.source_id: source for source in context.sources}
        extra_warnings: list[str] = []

        for tool_name, arguments in self._planned_tool_calls(context):
            if tool_name not in allowed_tool_names:
                continue
            execution = execute_tool(tool_name, arguments, context)
            tool_traces.append(execution.trace)
            for source in execution.sources:
                sources[source.source_id] = source
            if isinstance(execution.output, dict) and isinstance(execution.output.get("error"), str):
                extra_warnings.append(f"{tool_name}: {execution.output['error']}")
                continue
            if tool_name in tool_outputs:
                existing_output = tool_outputs[tool_name]
                if isinstance(existing_output, list):
                    existing_output.append(execution.output)
                else:
                    tool_outputs[tool_name] = [existing_output, execution.output]
            else:
                tool_outputs[tool_name] = execution.output

        card = self._build_card(request=request, context=context, tool_outputs=tool_outputs, tool_traces=tool_traces)
        response_id = self._response_id(request)
        warnings = dedupe_warnings(
            context.warnings,
            extra_warnings,
            ["Generated by Gamma's local mock Copilot provider; no external model inference was used."],
        )
        return CopilotResearchCardResult(
            domain=request.domain,
            current_tab=context.current_tab,
            status="ready",
            provider=self.provider_name,
            model=self.model,
            response_id=response_id,
            card=card,
            sources=list(sources.values()),
            tool_traces=tool_traces,
            warnings=warnings,
        )

    def _planned_tool_calls(self, context: CopilotContextBundle) -> list[tuple[str, dict[str, Any]]]:
        domain = context.domain
        if domain == "portfolio":
            return [
                ("get_portfolio_positions_summary", {}),
                ("get_portfolio_performance_context", {}),
            ]
        if domain == "research":
            return [
                ("get_research_scope_summary", {}),
                ("get_research_coverage_context", {}),
            ]
        if domain == "strategy_lab":
            calls: list[tuple[str, dict[str, Any]]] = [("get_strategy_lab_handoff_context", {})]
            if any(context.tool_state.get(key) for key in ("composition", "imported_result", "compare_result")):
                calls.append(("run_strategy_lab_backtest", {"result_kind": "auto"}))
            return calls
        if domain == "macro":
            calls: list[tuple[str, dict[str, Any]]] = [("get_macro_workspace_drilldown", {})]
            series_id = self._infer_macro_series_id(context.summary_data)
            if series_id:
                calls.append(("get_macro_series_history_summary", {"series_id": series_id, "region": None}))
            return calls
        if domain == "commodities":
            return [("get_commodities_workspace_summary", {})]
        if domain == "prediction_markets":
            return [
                ("get_prediction_market_history_summary", {}),
                ("get_prediction_market_flow_context", {}),
            ]
        if domain == "crypto":
            return [
                ("get_crypto_price_history_summary", {}),
                ("get_crypto_liquidity_context", {}),
                ("get_crypto_comparison_context", {}),
            ]
        if domain == "fundamentals":
            return [
                ("get_fundamentals_company_context", {}),
                ("get_fundamentals_statement_context", {}),
                ("get_fundamentals_peer_context", {}),
                ("get_fundamentals_dcf_context", {}),
                ("get_fundamentals_reverse_valuation_context", {}),
            ]
        if domain == "risk":
            return [
                ("get_risk_coverage_summary", {}),
                ("get_risk_contribution_summary", {}),
            ]
        if domain == "iv":
            return [
                ("get_iv_surface_context", {}),
                ("get_iv_session_status", {}),
            ]
        if domain == "synthesis":
            calls: list[tuple[str, dict[str, Any]]] = [("get_synthesis_scope_summary", {})]
            for item in self._as_list(context.summary_data.get("included_contexts")):
                included_domain = str(self._as_dict(item).get("domain") or "").strip()
                if included_domain:
                    calls.append(("get_synthesis_domain_context", {"domain": included_domain}))
            return calls
        return []

    def _build_card(
        self,
        *,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        domain = context.domain
        if domain == "portfolio":
            return self._build_portfolio_card(request, context, tool_outputs, tool_traces)
        if domain == "research":
            return self._build_research_card(request, context, tool_outputs, tool_traces)
        if domain == "macro":
            return self._build_macro_card(request, context, tool_outputs, tool_traces)
        if domain == "commodities":
            return self._build_commodities_card(request, context, tool_outputs, tool_traces)
        if domain == "prediction_markets":
            return self._build_prediction_card(request, context, tool_outputs, tool_traces)
        if domain == "crypto":
            return self._build_crypto_card(request, context, tool_outputs, tool_traces)
        if domain == "fundamentals":
            return self._build_fundamentals_card(request, context, tool_outputs, tool_traces)
        if domain == "risk":
            return self._build_risk_card(request, context, tool_outputs, tool_traces)
        if domain == "iv":
            return self._build_iv_card(request, context, tool_outputs, tool_traces)
        if domain == "strategy_lab":
            return self._build_strategy_lab_card(request, context, tool_outputs, tool_traces)
        if domain == "synthesis":
            return self._build_synthesis_card(request, context, tool_outputs, tool_traces)
        return self._fallback_card(request, context, tool_traces)

    def _build_portfolio_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        snapshot = self._as_dict(context.summary_data.get("snapshot"))
        performance = self._as_dict(tool_outputs.get("get_portfolio_performance_context")) or self._as_dict(
            context.summary_data.get("performance")
        )
        largest_position = self._as_dict(snapshot.get("largest_position"))
        largest_symbol = largest_position.get("symbol") or "the top position"
        cash_weight = self._as_float(snapshot.get("cash_weight"))
        relative_return = self._as_float(performance.get("relative_return"))
        benchmark = performance.get("benchmark_symbol") or "the benchmark"

        if cash_weight is not None and cash_weight >= 0.2:
            hypothesis = (
                "Cash and top-position concentration are large enough that deployment timing may matter more than broad market beta."
            )
        elif relative_return is not None and abs(relative_return) >= 0.03:
            hypothesis = (
                "Recent benchmark-relative slippage is large enough that the portfolio likely needs a top-exposure attribution pass."
            )
        else:
            hypothesis = "The active book is concentrated enough that top exposures and benchmark framing should be reviewed together."

        rationale = (
            f"The portfolio context includes {self._fmt_int(snapshot.get('positions_count'))} positions, "
            f"top exposure in {largest_symbol}, and a loaded performance overlay against {benchmark}."
        )
        required_data = [
            "Top exposures by base-market value",
            f"Benchmark-relative performance versus {benchmark}",
            "Cash weight and local-history drawdown context",
        ]
        confounders = [
            "Local history may be shorter than the current positioning regime.",
            "Benchmark-relative interpretation depends on the chosen benchmark.",
            "Unrealized P&L can overstate conviction changes during volatile sessions.",
        ]
        next_steps = [
            f"Review whether {largest_symbol} is driving most of the portfolio variance.",
            "Check whether cash weight is intentional dry powder or passive drag.",
            "Compare recent benchmark-relative drift against the local drawdown path.",
        ]
        caveats = [
            "This card was generated by Gamma's deterministic mock Copilot.",
            "It uses only the loaded Gamma portfolio context and read-only tools.",
        ]
        return ResearchCard(
            title=self._title("Portfolio", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=required_data,
            proposed_test=(
                f"Rank the largest positions by weight and unrealized P&L, then compare that concentration profile against "
                f"the recent relative return versus {benchmark}."
            ),
            confounders=confounders,
            next_steps=next_steps,
            caveats=caveats,
            source_backed_claims=[
                self._claim(
                    "Gamma has an active portfolio snapshot plus performance context available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "Any conclusion about sizing changes or redeployment still requires user judgment.",
            ],
        )

    def _build_research_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        research = self._as_dict(context.summary_data.get("research"))
        structure = self._as_dict(research.get("structure"))
        coverage = self._as_dict(tool_outputs.get("get_research_coverage_context")) or self._as_dict(
            research.get("coverage")
        )
        primary_symbol = research.get("primary_symbol") or "the active scope"
        scope_type = research.get("scope_type") or "research scope"
        top_weight = self._as_float(structure.get("top_weight"))
        effective_positions = self._as_float(structure.get("effective_positions"))

        if top_weight is not None and top_weight >= 0.5:
            hypothesis = "The active research scope is concentrated enough that a single-name driver may dominate the conclusion."
        elif effective_positions is not None and effective_positions >= 4:
            hypothesis = "The active research scope is diversified enough to justify a cleaner benchmark-relative comparison."
        else:
            hypothesis = "The active research scope is coherent enough to refine into a sharper benchmark-relative question."

        rationale = (
            f"Gamma already has a {scope_type.replace('_', ' ')} result for {primary_symbol}, "
            f"including structure, constituent contribution, and coverage diagnostics."
        )
        missing = coverage.get("missing_symbols") or []
        missing_label = ", ".join(str(item) for item in missing[:4]) if missing else "none"
        return ResearchCard(
            title=self._title("Research", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=[
                "Current weight structure",
                "Constituent return and weighted-return breakdown",
                "Coverage and benchmark-overlap diagnostics",
            ],
            proposed_test=(
                "Compare the top-weighted constituents against the weakest contributor, then check whether the observed "
                "conclusion survives the current coverage and benchmark-overlap constraints."
            ),
            confounders=[
                "Synthetic scopes can hide name-level concentration behind normalized weights.",
                f"Missing history currently reported: {missing_label}.",
                "Benchmark overlap can thin out faster than the headline constituent count implies.",
            ],
            next_steps=[
                "Inspect the weighted leader and worst constituent together rather than in isolation.",
                "Confirm whether missing symbols change the apparent edge.",
                "Decide whether the next run should tighten the scope or change the benchmark lens.",
            ],
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "It does not infer beyond the currently loaded research result and tool outputs.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma has an active research result plus scope and coverage drilldowns available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "The cleanest next research question depends on what benchmark or comparison set you actually care about.",
            ],
        )

    def _build_macro_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        focus_items = self._as_list(context.summary_data.get("focus_items"))
        top_divergences = self._as_list(context.summary_data.get("top_divergences"))
        upcoming_events = self._as_list(context.summary_data.get("upcoming_events"))
        region = context.summary_data.get("region") or "US"
        timeframe = context.summary_data.get("timeframe") or "3M"
        theme = context.summary_data.get("theme") or "all"
        lead_focus = self._as_dict(focus_items[0]) if focus_items else {}
        lead_divergence = self._as_dict(top_divergences[0]) if top_divergences else {}
        drilldown = self._as_dict(tool_outputs.get("get_macro_workspace_drilldown"))
        linked_markets = self._as_list(drilldown.get("linked_markets"))
        focus_title = lead_focus.get("title") or lead_divergence.get("headline") or "the current macro setup"

        hypothesis = (
            f"{focus_title} is the cleanest place to pressure-test the {region} {timeframe} macro narrative right now."
        )
        rationale = (
            f"The active Macro workspace already carries focus items, divergence rankings, events, and linked market context "
            f"for {region} over {timeframe} with theme `{theme}`."
        )
        next_steps = [
            f"Open the lead divergence around {focus_title} and compare it with the rest of the active theme map.",
            "Check whether the next official catalyst would confirm or break the current framing.",
            "Compare the macro read with any linked prediction-market alignment before over-interpreting it.",
        ]
        if linked_markets:
            next_steps[2] = "Compare the macro read with the linked prediction-market alignment before over-interpreting it."
        event_label = upcoming_events[0].get("title") if upcoming_events else "the next scheduled macro catalyst"
        return ResearchCard(
            title=self._title("Macro", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=[
                "Lead focus item and why-now framing",
                "Top divergence and comparison context",
                "Upcoming catalyst calendar and linked-market overlays",
            ],
            proposed_test=(
                f"Trace the top divergence through the active {timeframe} window, then compare that move against "
                f"{event_label} and any linked cross-market context."
            ),
            confounders=[
                "Macro coherence and lead/lag labels are heuristic, not causal inference.",
                "Regional depth is uneven, with US coverage generally deeper than EU or Global.",
                "Theme framing can change quickly around scheduled catalysts.",
            ],
            next_steps=next_steps,
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "It relies on the current Macro snapshot and read-only drilldowns only.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma has a live macro snapshot and macro drilldown context available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "The most important market narrative is still a research framing choice, not a model output.",
            ],
        )

    def _build_commodities_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        commodities = self._as_dict(context.summary_data.get("commodities"))
        drilldown = self._as_dict(tool_outputs.get("get_commodities_workspace_summary")) or commodities
        provider = self._as_dict(drilldown.get("provider"))
        selected_market = self._as_dict(drilldown.get("selected_market"))
        selected_curve = self._as_dict(drilldown.get("selected_curve"))
        spreads = self._as_list(drilldown.get("spreads"))
        inventories = self._as_list(drilldown.get("inventories"))
        selected_name = selected_market.get("name") or selected_market.get("symbol") or "the selected commodity"
        curve_state = selected_curve.get("shape_label") or selected_market.get("curve_state") or "unavailable"
        coverage_status = provider.get("coverage_status") or "unknown"

        hypothesis = (
            f"{selected_name} should be framed through curve shape, spreads, and inventory context before drawing a commodity-market conclusion."
        )
        if curve_state in {"backwardation", "contango"}:
            hypothesis = (
                f"{selected_name} has a {curve_state} curve, so the cleanest research question is whether spreads and inventories confirm that term-structure signal."
            )

        rationale = (
            f"The loaded Commodities workspace uses {coverage_status} coverage, includes {len(spreads)} spread rows and "
            f"{len(inventories)} inventory or fundamental rows, and remains a read-only research context."
        )
        return ResearchCard(
            title=self._title("Commodities", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=[
                "Selected market summary and curve state",
                "Calendar and inter-commodity spreads",
                "Inventory and event context with provider caveats",
            ],
            proposed_test=(
                f"Compare {selected_name}'s curve state against the front spread, selected calendar spreads, and linked inventory signal, then check whether events or cross-domain links change the framing."
            ),
            confounders=[
                "Sample or proxy data can make spread and curve context illustrative rather than live market evidence.",
                "Roll-yield and seasonal inventory readings are Gamma heuristics, not realized return or official surprise models.",
                "Commodity links to macro, maritime, and prediction markets are research handoffs, not causal conclusions.",
            ],
            next_steps=[
                "Inspect the selected curve nodes and front spread before using the headline price.",
                "Compare product cracks or metals ratios against their z-score and percentile caveats.",
                "Check provider coverage and source timestamp before treating the workspace as fresh.",
            ],
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "Gamma Commodities is read-only and does not expose order placement, trading automation, or strategy execution.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma has a loaded Commodities workspace and read-only commodity drilldown context available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "The best commodity thesis still depends on whether the chosen provider is sample, proxy, or official partial coverage.",
            ],
        )

    def _build_prediction_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        selected_market = self._as_dict(context.summary_data.get("selected_market"))
        history = self._as_dict(tool_outputs.get("get_prediction_market_history_summary")) or self._as_dict(
            context.summary_data.get("history_summary")
        )
        flow = self._as_dict(tool_outputs.get("get_prediction_market_flow_context"))
        wallet_summary = self._as_dict(flow.get("wallet_summary")) or self._as_dict(context.summary_data.get("wallet_summary"))
        related = self._as_list(flow.get("related_markets")) or self._as_list(context.summary_data.get("related_markets"))
        title = selected_market.get("title") or "Selected market"
        venue = selected_market.get("venue") or "venue"
        change = self._as_float(history.get("change"))
        participant_share = self._as_float(wallet_summary.get("top_participant_share"))

        if change is not None and abs(change) >= 0.08:
            hypothesis = "The selected market is still repricing enough that recent history and related-market checks matter more than the static headline probability."
        elif participant_share is not None and participant_share >= 0.25:
            hypothesis = "Flow concentration is high enough that participant behavior may matter as much as the current midpoint."
        else:
            hypothesis = "The selected market needs to be framed through price history, related contracts, and flow rather than current probability alone."

        rationale = (
            f"Gamma already has the {venue} contract detail for {title}, plus current history, flow, related-market, and calibration context."
        )
        relationship = self._as_dict(related[0]).get("relationship") if related else "related-market"
        return ResearchCard(
            title=self._title("Prediction Market", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=[
                "Primary-outcome probability history",
                "Wallet or taker-flow concentration context",
                "Related-market gaps and venue calibration",
            ],
            proposed_test=(
                f"Compare the current market against its recent range, then test whether {relationship} relationships "
                "and participant concentration reinforce or weaken the repricing story."
            ),
            confounders=[
                "Venue freshness and history lag can distort apparent signal quality.",
                "Wallet-level depth differs by venue, especially between Polymarket and Kalshi.",
                "Calibration coverage is still thin and venue dependent.",
            ],
            next_steps=[
                "Inspect whether the recent move is large relative to the loaded history window.",
                "Review the top participant rows before treating flow as confirming evidence.",
                "Check whether the related-market gap is thematic noise or an actual consistency question.",
            ],
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "It uses only Gamma's read-only prediction-market context and drilldowns.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma has selected-market detail plus history and flow drilldowns available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "Any edge claim still depends on the next catalyst and on whether related markets are truly comparable.",
            ],
        )

    def _build_crypto_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        selected_token = self._as_dict(context.summary_data.get("selected_token"))
        history = self._as_dict(tool_outputs.get("get_crypto_price_history_summary")) or self._as_dict(
            context.summary_data.get("price_history_summary")
        )
        liquidity = self._as_dict(tool_outputs.get("get_crypto_liquidity_context")) or self._as_dict(
            context.summary_data.get("liquidity_summary")
        )
        comparison = self._as_dict(tool_outputs.get("get_crypto_comparison_context")) or self._as_dict(
            context.summary_data.get("comparison_summary")
        )
        name = selected_token.get("name") or "the selected token"
        chain = selected_token.get("chain") or selected_token.get("asset_platform_id") or "its primary chain"
        turnover_ratio = self._as_float(selected_token.get("turnover_ratio_24h"))
        change_pct = self._as_float(history.get("change_pct"))
        dominant_dex = liquidity.get("dominant_dex") or "the dominant pool venue"
        comparison_label = comparison.get("target_label") or "its default comparison target"

        if change_pct is not None and abs(change_pct) >= 15.0:
            hypothesis = "The selected token is moving enough that price path and turnover matter more than the static market-cap snapshot."
        elif turnover_ratio is not None and turnover_ratio >= 0.2:
            hypothesis = "Turnover is elevated enough that liquidity depth and flow context should be checked before leaning on the move."
        else:
            hypothesis = "The selected token should be framed through price path, narrative tags, liquidity, and relative context together."

        rationale = (
            f"Gamma already has normalized crypto detail for {name} on {chain}, plus price history, DEX liquidity context, "
            f"and a default comparison versus {comparison_label}."
        )
        return ResearchCard(
            title=self._title("Crypto", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=[
                "Normalized token profile and category tags",
                "30D price, market-cap, and volume history",
                f"DEX liquidity context from {dominant_dex}",
            ],
            proposed_test=(
                f"Compare {name}'s recent price path and 24H turnover against the default comparison target, then test whether "
                "DEX reserve depth and pool flow confirm or challenge that read."
            ),
            confounders=[
                "CoinGecko category labels and GeckoTerminal pool matching can be incomplete for long-tail assets.",
                "DEX context can fall back to heuristic search when an exact contract lookup is unavailable.",
                "Gamma screen score and basket comparisons are Gamma-defined research heuristics, not execution signals.",
            ],
            next_steps=[
                "Check whether the recent move is large relative to the loaded 30D path.",
                "Review dominant-pool reserve and 24H turnover before treating the move as broadly liquid.",
                "Use the default comparison target as a frame, then decide whether a narrower peer set is needed.",
            ],
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "It uses only Gamma's read-only crypto research context and drilldowns.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma has selected-token detail plus crypto history, liquidity, and comparison drilldowns available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "Any narrative conclusion still depends on whether the comparison target matches the thesis you want to test.",
            ],
        )

    def _build_fundamentals_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        summary = context.summary_data
        company_context = self._as_dict(tool_outputs.get("get_fundamentals_company_context"))
        statement_context = self._as_dict(tool_outputs.get("get_fundamentals_statement_context"))
        peer_context = self._as_dict(tool_outputs.get("get_fundamentals_peer_context"))
        dcf_context = self._as_dict(tool_outputs.get("get_fundamentals_dcf_context"))
        reverse_context = self._as_dict(tool_outputs.get("get_fundamentals_reverse_valuation_context"))

        company = self._as_dict(company_context.get("company")) or self._as_dict(summary.get("company"))
        ticker = company.get("ticker") or summary.get("ticker") or "the selected company"
        name = company.get("name") or ticker
        peer_basket = self._as_dict(peer_context.get("peer_basket")) or self._as_dict(summary.get("peer_basket"))
        peer_order = self._as_list(peer_basket.get("display_order")) or self._as_list(peer_basket.get("tickers"))
        metric_families = self._as_list(peer_context.get("metric_families"))
        dcf = self._as_dict(summary.get("dcf"))
        active_scenario = dcf_context.get("active_scenario_id") or dcf.get("active_scenario_id") or "Base"
        snapshots = self._as_list(dcf_context.get("snapshots"))
        drivers = self._as_list(reverse_context.get("drivers")) or self._as_list(
            self._as_dict(summary.get("reverse_valuation")).get("drivers")
        )
        first_driver = self._as_dict(drivers[0]) if drivers else {}
        driver_label = first_driver.get("label") or "market-implied expectations"
        driver_value = first_driver.get("display_value") or "unavailable"
        gap_metrics = self._as_list(reverse_context.get("scenario_gap_metrics"))
        gap_label = self._as_dict(gap_metrics[0]).get("display_value") if gap_metrics else None
        trace_sample = self._as_list(statement_context.get("trace_sample"))
        coverage_warnings = self._as_list(statement_context.get("coverage_warnings"))

        if first_driver.get("success") is False:
            hypothesis = f"{name} needs a fundamentals review because the current market price is outside at least one bounded reverse-valuation solve."
        elif gap_label:
            hypothesis = f"{name}'s market price should be tested against the {active_scenario} DCF and the implied {driver_label} of {driver_value}."
        else:
            hypothesis = f"{name} should be framed through normalized filings, peer context, DCF assumptions, and reverse valuation together."

        peer_count = len(peer_order)
        family_label = ", ".join(str(item) for item in metric_families[:4]) or "valuation and operating"
        rationale = (
            f"Gamma has a read-only fundamentals bundle for {ticker}: normalized SEC statements, "
            f"{peer_count} peer basket entries, a {active_scenario} DCF case, and reverse-valuation outputs."
        )
        proposed_test = (
            f"Compare the implied {driver_label} ({driver_value}) against the {active_scenario} DCF assumptions, "
            f"then check whether peer {family_label} metrics support or challenge that setup."
        )
        if snapshots:
            proposed_test += " Use the saved DCF snapshots as the audit trail for prior assumptions."

        required_data = [
            "Company filings and raw-versus-normalized source trace",
            "Normalized annual statements with coverage warnings",
            "Persistent peer basket and comparison diagnostics",
            "Bear/Base/Bull DCF summaries and saved snapshots",
            "Reverse valuation drivers and WACC/terminal-growth sensitivity",
        ]
        if not trace_sample:
            required_data[0] = "Company filings and source trace, noting any unavailable trace rows"

        confounders = [
            "Sparse SEC taxonomy coverage can make normalized statement comparisons incomplete.",
            "IBKR or mock market context affects price, share-count, and net-debt framing.",
            "Peer baskets are research scaffolding; business-model comparability still needs judgment.",
        ]
        if coverage_warnings:
            confounders.insert(0, "Coverage warnings are present in the raw-versus-normalized inspection payload.")

        next_steps = [
            "Open Reference / Filings to inspect filing chronology, amendment markers, and source trace rows.",
            "Use Peers to review missing-data diagnostics before leaning on a relative valuation read.",
            f"Use Reverse Valuation to compare implied expectations against the {active_scenario} DCF case.",
        ]
        caveats = [
            "This card was generated by Gamma's deterministic mock Copilot.",
            "It uses only Gamma's read-only fundamentals context and drilldowns.",
            "It is research framing, not a recommendation or execution signal.",
        ]
        return ResearchCard(
            title=self._title("Fundamentals", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=required_data,
            proposed_test=proposed_test,
            confounders=confounders,
            next_steps=next_steps,
            caveats=caveats,
            source_backed_claims=[
                self._claim(
                    "Gamma has company, statement, peer, DCF, and reverse-valuation drilldowns available for this Fundamentals card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "Any valuation conclusion still depends on whether the normalized filing history and peer set match the thesis under review.",
            ],
        )

    def _build_risk_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        risk = self._as_dict(context.summary_data.get("risk"))
        coverage = self._as_dict(tool_outputs.get("get_risk_coverage_summary")) or self._as_dict(risk.get("coverage"))
        contributions = self._as_dict(tool_outputs.get("get_risk_contribution_summary"))
        coverage_ratio = self._as_float(coverage.get("risk_coverage_ratio"))
        top_contributions = self._as_list(contributions.get("top_contributions"))
        top_symbol = self._as_dict(top_contributions[0]).get("symbol") if top_contributions else "the top contributor"

        if coverage_ratio is not None and coverage_ratio < 0.8:
            hypothesis = "Risk interpretation is currently constrained more by incomplete coverage than by the headline VaR figure."
        else:
            hypothesis = "Top contribution concentration is likely the cleanest place to challenge the active risk result."

        rationale = (
            "Gamma already has an active risk computation with coverage, benchmark, contribution, exclusion, and Monte Carlo context."
        )
        return ResearchCard(
            title=self._title("Risk", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=[
                "Risk coverage ratio and exclusions",
                "Top contribution-to-risk ranking",
                "Monte Carlo context and benchmark overlap",
            ],
            proposed_test=(
                f"Check whether {top_symbol} dominates the top contribution ranking and then compare that concentration "
                "against the current coverage ratio and excluded-asset list."
            ),
            confounders=[
                "Incomplete coverage can make scaled total estimates look more precise than they are.",
                "Benchmark overlap can be thinner than the portfolio snapshot suggests.",
                "Linear or history-based risk models do not capture every path-dependent payoff.",
            ],
            next_steps=[
                "Review excluded assets before relying on the headline risk number.",
                "Inspect whether the top contribution cluster is a single-name issue or a factor cluster.",
                "Use the Monte Carlo output as context, not as a claim of distributional certainty.",
            ],
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "It remains anchored to Gamma's current risk result and read-only drilldowns.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma has active risk coverage and contribution drilldowns available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "The best hedge question still depends on what risk you actually want to neutralize.",
            ],
        )

    def _build_iv_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        iv_summary = self._as_dict(context.summary_data.get("iv"))
        surface = self._as_dict(tool_outputs.get("get_iv_surface_context")) or iv_summary
        session = self._as_dict(tool_outputs.get("get_iv_session_status")) or self._as_dict(iv_summary.get("session"))
        symbol = surface.get("symbol") or session.get("active_symbol") or "the active symbol"
        selected_expiry = surface.get("selected_expiry") or "the front expiry"
        atm_strike = surface.get("atm_strike")
        running = bool(session.get("running"))

        hypothesis = "The active surface is useful for framing skew and term-structure questions, but not for inferring valuation certainty."
        rationale = (
            f"Gamma already has an options surface for {symbol}, including the front slice around {selected_expiry}, "
            f"ATM term structure, and session state."
        )
        next_steps = [
            "Compare front-slice skew against the ATM term structure before making a surface claim.",
            "Check whether delayed or session-state caveats limit what the surface is saying.",
            "Decide whether the next question is about level, skew, or term structure rather than all three at once.",
        ]
        if running:
            next_steps[1] = "Check whether the live session state or market-data mode changes how much confidence to place in the surface."
        return ResearchCard(
            title=self._title("Options", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=[
                "Front-expiry slice around the ATM strike",
                "ATM term structure",
                "Current session state and market-data mode",
            ],
            proposed_test=(
                f"Use {selected_expiry} and the ATM strike around {atm_strike or 'spot'} as the anchor, then compare "
                "front-slice shape versus the broader term structure before interpreting skew."
            ),
            confounders=[
                "Sparse or delayed surface points can distort local shape.",
                "The Options tab is an inspection tool, not a full pricing or Greeks stack.",
                "Session state matters when interpreting whether a surface is fresh or stale.",
            ],
            next_steps=next_steps,
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "It uses only the loaded options surface and read-only session context.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma has an active options surface and session drilldowns available for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "Any options trade conclusion still requires external pricing, liquidity, and execution judgment.",
            ],
        )

    def _build_strategy_lab_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        handoffs = self._as_dict(tool_outputs.get("get_strategy_lab_handoff_context")) or self._as_dict(
            context.summary_data.get("handoff_context")
        )
        backtest = self._as_dict(tool_outputs.get("run_strategy_lab_backtest"))
        current_count = int(self._as_float(handoffs.get("current_count")) or 0)
        status_counts = self._as_dict(handoffs.get("status_counts"))
        resolved_count = int(self._as_float(status_counts.get("resolved")) or 0)
        pending_count = int(self._as_float(status_counts.get("pending")) or 0) + int(
            self._as_float(status_counts.get("resolving")) or 0
        )
        unsupported_count = int(self._as_float(status_counts.get("unsupported")) or 0)
        context_state = handoffs.get("context_state") or "no_current_handoffs"
        if resolved_count and pending_count:
            hypothesis = "Strategy Lab has mixed handoff context: resolved objects can be cited, while pending items still need resolver confirmation."
        elif resolved_count:
            hypothesis = "Strategy Lab has resolved handoff context that Copilot can cite as Gamma-validated research objects."
        elif pending_count:
            hypothesis = "Strategy Lab has pending handoff intent, but Copilot should treat it as unresolved until the resolver runs."
        elif backtest:
            hypothesis = "Strategy Lab has an active analysis result that can be reviewed as a read-only backtest."
        else:
            hypothesis = "Strategy Lab context is available, but no resolved handoff or active backtest is loaded."

        rationale = (
            f"Gamma reports Strategy Lab handoff context state `{context_state}` with {current_count} current item(s), "
            f"{resolved_count} resolved, {pending_count} pending, and {unsupported_count} unsupported."
        )
        required_data = [
            "Strategy Lab handoff queue state",
            "Resolved handoff object identities, coverage, provenance, and warnings",
            "Active import/composition/compare result when available",
        ]
        if not resolved_count:
            required_data[1] = "Resolver output before treating any pending handoff as a validated object"
        return ResearchCard(
            title=self._title("Strategy Lab", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=required_data,
            proposed_test=(
                "Separate pending intent from resolved objects, then cite only resolved handoff sources or active Strategy Lab analytics "
                "when drawing conclusions."
            ),
            confounders=[
                "Pending handoffs may resolve to unsupported context or include resolver warnings.",
                "Unsupported handoffs are reference-only and should not become weighted return legs.",
                "Accepted composer rows are separate from the inbound queue once the user accepts them.",
            ],
            next_steps=[
                "Resolve pending Strategy Lab handoffs before using them as research evidence.",
                "Inspect resolved object coverage and warnings before composing a book.",
                "Use active composition/backtest results separately from unresolved inbound queue state.",
            ],
            caveats=[
                "This card was generated by Gamma's deterministic mock Copilot.",
                "Strategy Lab handoff context is read-only and does not create orders, broker mutations, or execution instructions.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma exposed explicit Strategy Lab handoff queue state and source references for this card.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "The strongest Strategy Lab conclusion depends on whether the resolved objects have enough coverage for the thesis.",
            ],
        )

    def _build_synthesis_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_outputs: dict[str, Any],
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        scope = self._as_dict(tool_outputs.get("get_synthesis_scope_summary")) or self._as_dict(context.summary_data)
        included_contexts = self._as_list(scope.get("included_contexts"))
        domain_outputs = {
            str(self._as_dict(item).get("domain") or "").strip(): self._as_dict(item)
            for item in self._as_list(tool_outputs.get("get_synthesis_domain_context"))
            if str(self._as_dict(item).get("domain") or "").strip()
        }
        included_labels = [
            str(self._as_dict(item).get("label") or self._as_dict(item).get("domain") or "Context")
            for item in included_contexts
        ]
        included_domains = [
            str(self._as_dict(item).get("domain") or "").strip()
            for item in included_contexts
            if str(self._as_dict(item).get("domain") or "").strip()
        ]
        lead_label = included_labels[0] if included_labels else "the active Gamma contexts"
        compare_label = included_labels[1] if len(included_labels) > 1 else lead_label
        active_tab = scope.get("active_tab") or "the shell"
        scope_size = len(included_contexts)
        warning_count = len(self._as_list(scope.get("warnings")))

        domain_notes: list[str] = []
        for domain in included_domains[:3]:
            synthesis_domain = domain_outputs.get(domain, {})
            summary = self._as_dict(synthesis_domain.get("summary"))
            warnings = self._as_list(synthesis_domain.get("warnings"))
            if summary:
                domain_notes.append(
                    f"{domain.replace('_', ' ').title()} contributes structured Gamma summary data with {len(warnings)} warnings."
                )

        scope_label = ", ".join(included_labels[:3]) if included_labels else "the selected Gamma scope"
        if scope_size > 3:
            scope_label = f"{scope_label}, and {scope_size - 3} more"

        hypothesis = (
            f"The cross-context read should be framed as a synthesis between {lead_label} and {compare_label}, "
            "not as isolated tab-level conclusions."
        )
        rationale = (
            f"Gamma assembled a read-only synthesis scope across {scope_size} loaded contexts from {active_tab}, "
            "keeping provenance, warnings, and source references attached to each included domain."
        )
        confounders = [
            "Freshness and warning depth can differ across the included Gamma contexts.",
            "Cross-context alignment is a research framing, not a causal proof.",
            "The synthesis only reflects contexts already loaded into Gamma at request time.",
        ]
        if warning_count:
            confounders[0] = f"Freshness and warning depth are uneven across the included contexts ({warning_count} active warning(s))."
        next_steps = [
            f"Use the current scope ({scope_label}) to isolate the strongest agreement and the strongest contradiction.",
            "Follow up on the domain with the weakest provenance or the heaviest warning burden before tightening the thesis.",
            "Narrow the synthesis scope if the current cross-context brief is still too broad for a testable next step.",
        ]
        required_data = [
            "Included Gamma domain summaries and fingerprints",
            "Attached source references and warnings for each included domain",
            "Domain-specific drilldowns for the strongest agreement or contradiction",
        ]
        if domain_notes:
            required_data[2] = "Domain-specific drilldowns for the strongest agreement or contradiction, especially where warnings differ"
        return ResearchCard(
            title=self._title("Synthesis", request.prompt),
            hypothesis=hypothesis,
            rationale=rationale,
            required_data=required_data,
            proposed_test=(
                "Compare the included domains side by side, identify the highest-conviction overlap, then pressure-test whether "
                "the most constrained or warning-heavy domain changes the conclusion."
            ),
            confounders=confounders,
            next_steps=next_steps,
            caveats=[
                "This synthesis card was generated by Gamma's deterministic mock Copilot.",
                "It remains read-only and grounded only in the selected Gamma contexts and synthesis drilldowns.",
            ],
            source_backed_claims=[
                self._claim(
                    "Gamma assembled a multi-domain synthesis scope with attached domain-level provenance and drilldowns.",
                    context,
                    tool_traces,
                )
            ],
            inferred_claims=[
                "The best cross-context thesis still depends on which disagreement you choose to prioritize.",
                *domain_notes[:2],
            ],
        )

    def _fallback_card(
        self,
        request: CopilotResearchCardRequest,
        context: CopilotContextBundle,
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchCard:
        return ResearchCard(
            title=self._title("Copilot", request.prompt),
            hypothesis="The active Gamma context is available for structured review.",
            rationale="Gamma has enough current workspace context to produce a deterministic local research card.",
            required_data=["Current workspace context"],
            proposed_test="Review the current workspace context and decide which follow-up diagnostic matters most.",
            confounders=["This fallback does not use domain-specific heuristics."],
            next_steps=["Open a domain with richer tab-specific context if you need a sharper card."],
            caveats=["This card was generated by Gamma's deterministic mock Copilot."],
            source_backed_claims=[self._claim("Gamma has current workspace context available for this card.", context, tool_traces)],
            inferred_claims=[],
        )

    def _claim(
        self,
        text: str,
        context: CopilotContextBundle,
        tool_traces: list[CopilotToolTrace],
    ) -> ResearchClaim:
        evidence_refs: list[str] = []
        for source in context.sources[:2]:
            evidence_refs.append(source.source_id)
        for trace in tool_traces:
            for source_id in trace.source_ids:
                if source_id not in evidence_refs:
                    evidence_refs.append(source_id)
        return ResearchClaim(claim=text, evidence_refs=evidence_refs)

    def _infer_macro_series_id(self, summary_data: dict[str, Any]) -> str | None:
        for card in self._as_list(summary_data.get("snapshot_cards")):
            for metric in self._as_list(self._as_dict(card).get("metrics")):
                series_id = str(self._as_dict(metric).get("series_id") or "").strip()
                if series_id:
                    return series_id
        rates_policy = self._as_dict(summary_data.get("rates_policy"))
        for key in ("policy_metrics", "real_yield_metrics"):
            for metric in self._as_list(rates_policy.get(key)):
                series_id = str(self._as_dict(metric).get("series_id") or "").strip()
                if series_id:
                    return series_id
        return None

    def _title(self, domain_label: str, prompt: str | None) -> str:
        prompt_text = str(prompt or "").strip()
        if not prompt_text:
            return f"{domain_label} Research Card"
        trimmed = " ".join(prompt_text.split())
        return f"{domain_label}: {trimmed[:68]}"

    def _response_id(self, request: CopilotResearchCardRequest) -> str:
        seed = "|".join(
            [
                str(request.user_session_id or "anonymous"),
                str(request.domain or ""),
                str(request.previous_response_id or ""),
                str(request.prompt or ""),
            ]
        )
        digest = sha256(seed.encode("utf-8")).hexdigest()[:16]
        return f"mock_{request.domain}_{digest}"

    @staticmethod
    def _as_dict(value: Any) -> dict[str, Any]:
        return value if isinstance(value, dict) else {}

    @staticmethod
    def _as_list(value: Any) -> list[Any]:
        return value if isinstance(value, list) else []

    @staticmethod
    def _as_float(value: Any) -> float | None:
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return None
        if numeric != numeric:
            return None
        return numeric

    @staticmethod
    def _fmt_int(value: Any) -> str:
        try:
            return f"{int(value):d}"
        except (TypeError, ValueError):
            return "0"
