from __future__ import annotations

MAX_CRYPTO_PORTFOLIO_POSITIONS = 100
MAX_CRYPTO_WORKSPACE_LIMIT = 100
MAX_PREDICTION_COMPARISON_LEGS = 6
MAX_PREDICTION_MARKET_LIMIT = 100
MAX_PREDICTION_MARKET_VENUES = 20
MAX_REQUEST_TEXT_CHARS = 256
MAX_RISK_BETA_WINDOW_DAYS = 756
MAX_RISK_HORIZON_DAYS = 252
MAX_RISK_LOOKBACK_DAYS = 2520
MAX_RISK_MC_HORIZON_DAYS = 252
MAX_RISK_MC_SIMULATIONS = 20_000
MAX_STRATEGY_LAB_ROW_FIELDS = 64
MAX_STRATEGY_LAB_ROW_TEXT_CHARS = 1024
MAX_STRATEGY_LAB_ROWS = 10_000
